scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.purpleSwitchDown, function (sprite, location) {
    tiles.setCurrentTilemap(tilemap`level1`)
    tiles.placeOnRandomTile(mySprite, sprites.dungeon.chestOpen)
    music.powerDown.play()
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.chestClosed, function (sprite, location) {
    game.over(true)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.hazardLava1, function (sprite, location) {
    game.over(false)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.purpleSwitchUp, function (sprite, location) {
    tiles.setCurrentTilemap(tilemap`level1`)
    tiles.placeOnRandomTile(mySprite, sprites.dungeon.chestOpen)
    music.powerUp.play()
})
let mySprite: Sprite = null
mySprite = sprites.create(img`
    . . . 6 6 . . . . 
    . . . . 6 . . . . 
    . . . 9 8 9 . . . 
    . . 9 8 8 8 9 . . 
    . 9 6 6 8 8 8 9 . 
    . 9 6 6 6 8 8 9 . 
    . 9 6 6 6 8 8 9 . 
    . . 9 6 6 6 9 . . 
    . . . 9 9 9 . . . 
    `, SpriteKind.Player)
controller.moveSprite(mySprite)
let monster = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
tiles.setCurrentTilemap(tilemap`level1`)
tiles.placeOnRandomTile(mySprite, sprites.dungeon.chestOpen)
tiles.placeOnRandomTile(monster, sprites.dungeon.collectibleInsignia)
scene.cameraFollowSprite(mySprite)
forever(function () {
    monster.follow(mySprite)
})
